### ISSUE TITLE
Create database table for users questions

### ISSUE THREAD

**Issue by fccoelho** [AlertaDengue/vigibot#2]
Create a table for users question coming from either twitter or telegram

schema:

id | userid | network | question | timestamp
--------------------------------------------------------

Where:

- `id` is a primary autoincrementing key
-  `network` is varchar(16) "twitter" ou "telegram"
- `question` text is the question
- `timestamp` is an automatic timestamp

this table will help us analyze user interests and improve the training corpus.

**Comment by fccoelho** [comment]
@esloch and @eltonn Do you think adding a new table to the vigibot db will affect our bucardo synchronization?

**Comment by fccoelho** [comment]
Proposed sql code:
```sql
CREATE TABLE IF NOT EXISTS pergunta(
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(32) NOT NULL,
    network VARCHAR(16) NOT NULL,
    pergunta TEXT NOT NULL,
    datetime TIMESTAMP NOT NULL DEFAULT NOW() 
)
```

**Comment by esloch** [comment]
> @esloch e @eltonn Você acha que adicionar uma nova tabela ao banco de dados vigibot afetará a sincronização do bucardo?

I'm not sure, once sync is started, it may be necessary to execute the command ```bucardo add table``` on replicated database...
@eltonn, can you do a test?

**Comment by fccoelho** [comment]
If it is only a matter of doing a `bucardo add table` then I think it is safe to create this table. But I'll wait for @eltonn 's feedback.

**Comment by fccoelho** [comment]
tabela criada

+----------+-----------------------------+--------------------------------------------------------+
| Column   | Type                        | Modifiers                                              |
|----------+-----------------------------+--------------------------------------------------------|
| id       | bigint                      |  not null default nextval('pergunta_id_seq'::regclass) |
| username | character varying(32)       |  not null                                              |
| network  | character varying(16)       |  not null                                              |
| pergunta | text                        |  not null                                              |
| datetime | timestamp without time zone |  not null default now()                                |
+----------+-----------------------------+--------------------------------------------------------+
Indexes:
    "pergunta_pkey" PRIMARY KEY, btree (id)
    "pergunta_datetime_idx" btree (datetime)
    "pergunta_network_idx" btree (network)
